export const flutterStateManagementSkillTemplate = (prodUrl: string, displayName: string, description: string) => [
  '---',
  'name: ' + displayName,
  'description: ' + description,
  '---',
  '',
  '# Flutter State Management',
  '',
  '## BLoC Pattern',
  '',
  '### When to Use',
  '- Complex business logic',
  '- Need for event-driven architecture',
  '- Team collaboration',
  '- Testing is critical',
  '',
  '## Riverpod',
  '',
  '```dart',
  '// Provider',
  'final counterProvider = StateNotifierProvider<CounterNotifier, int>((ref) {',
  '  return CounterNotifier();',
  '});',
  '',
  'class CounterNotifier extends StateNotifier<int> {',
  '  CounterNotifier() : super(0);',
  '  ',
  '  void increment() => state++;',
  '}',
  '',
  '// Consumer',
  'class CounterWidget extends ConsumerWidget {',
  '  @override',
  '  Widget build(BuildContext context, WidgetRef ref) {',
  '    final count = ref.watch(counterProvider);',
  '    ',
  '    return ElevatedButton(',
  '      onPressed: () => ref.read(counterProvider.notifier).increment(),',
  '      child: Text("Count: $count"),',
  '    );',
  '  }',
  '}',
  '```',
  '',
  '## Best Practices',
  '',
  '1. **Immutable State** - Always create new state objects',
  '2. **Single Source of Truth** - One state per feature',
  '3. **Dispose Properly** - Always close blocs and dispose controllers',
].join('\n')
