export const flutterExpertSkillTemplate = (prodUrl: string, displayName: string, description: string) => [
  '---',
  'name: ' + displayName,
  'description: ' + description,
  '---',
  '',
  '# Flutter Expert',
  '',
  '## When to Use This Skill',
  '',
  'Use this skill when:',
  '- Building Flutter mobile or web applications',
  '- Implementing responsive UI with Material Design 3',
  '- Managing state with BLoC, Riverpod, or Provider',
  '- Optimizing app performance and reducing rebuilds',
  '',
  '## Core Principles',
  '',
  '### Widget Design',
  '- Prefer StatelessWidget when possible',
  '- Use const constructors aggressively',
  '- Keep widgets small and focused',
  '',
  '### State Management',
  '- Simple local state: setState or ValueNotifier',
  '- Medium complexity: Riverpod or Bloc',
  '- Complex apps: Bloc with Clean Architecture',
  '',
  '### Performance',
  '- Use ListView.builder for long lists',
  '- Cache network images',
  '- Minimize widget rebuilds with const',
  '',
  '## Package Recommendations',
  '- HTTP: dio or http',
  '- State Management: flutter_bloc, hooks_riverpod',
  '- Navigation: go_router',
  '- Storage: hive, shared_preferences',
].join('\n')
