export const flutterPerformanceSkillTemplate = (prodUrl: string, displayName: string, description: string) => [
  '---',
  'name: ' + displayName,
  'description: ' + description,
  '---',
  '',
  '# Flutter Performance',
  '',
  '## Rendering Optimization',
  '',
  '### 1. Minimize Rebuilds',
  '```dart',
  '// Good - only rebuilds changed items',
  'ListView.builder(',
  '  itemCount: items.length,',
  '  itemBuilder: (context, index) {',
  '    return ListItem(item: items[index]);',
  '  },',
  ')',
  '```',
  '',
  '### 2. Use const Constructors',
  '```dart',
  'const Text("Hello")',
  'const SizedBox(width: 16)',
  '```',
  '',
  '### 3. RepaintBoundary',
  '```dart',
  'RepaintBoundary(',
  '  child: ComplexWidget(),',
  ')',
  '```',
  '',
  '## Memory Optimization',
  '',
  '### Image Caching',
  '```dart',
  'CachedNetworkImage(',
  '  imageUrl: url,',
  '  memCacheWidth: 800,',
  '  placeholder: (context, url) => CircularProgressIndicator(),',
  ')',
  '```',
  '',
  '## List Performance',
  '',
  '```dart',
  'ListView.builder(',
  '  itemCount: 10000,',
  '  addAutomaticKeepAlives: false,',
  '  addRepaintBoundaries: true,',
  '  cacheExtent: 200,',
  '  itemBuilder: (context, index) {',
  '    return ListTile(title: Text("Item $index"));',
  '  },',
  ')',
  '```',
].join('\n')
