export const flutterUiUxSkillTemplate = (prodUrl: string, displayName: string, description: string) => [
  '---',
  'name: ' + displayName,
  'description: ' + description,
  '---',
  '',
  '# Flutter UI/UX',
  '',
  '## Material Design 3',
  '',
  '### Theme Setup',
  '```dart',
  'class AppTheme {',
  '  static ThemeData get lightTheme {',
  '    return ThemeData(',
  '      useMaterial3: true,',
  '      colorScheme: ColorScheme.fromSeed(',
  '        seedColor: Colors.blue,',
  '        brightness: Brightness.light,',
  '      ),',
  '    );',
  '  }',
  '}',
  '```',
  '',
  '### Responsive Design',
  '```dart',
  'class ResponsiveBuilder extends StatelessWidget {',
  '  final Widget mobile;',
  '  final Widget? tablet;',
  '  final Widget? desktop;',
  '  ',
  '  static bool isMobile(BuildContext context) => ',
  '    MediaQuery.of(context).size.width < 650;',
  '  ',
  '  @override',
  '  Widget build(BuildContext context) {',
  '    if (isDesktop(context)) return desktop ?? tablet ?? mobile;',
  '    if (isTablet(context)) return tablet ?? mobile;',
  '    return mobile;',
  '  }',
  '}',
  '```',
  '',
  '## Animations',
  '',
  '### Hero Animations',
  '```dart',
  'Hero(',
  '  tag: "image-${item.id}",',
  '  child: Image.network(item.imageUrl),',
  ')',
  '```',
].join('\n')
