import { chromium } from "/var/www/flutter-vibe-code/ide/node_modules/.pnpm/playwright@1.59.1/node_modules/playwright/index.mjs"
const browser = await chromium.launch({ headless: true, executablePath: "/usr/bin/google-chrome", args: ["--no-sandbox","--disable-setuid-sandbox"] })
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 })
const page = await ctx.newPage()
await page.goto("https://fluttervibecode.dpdns.org/sign-in", { waitUntil: "domcontentloaded", timeout: 30000 })
await page.waitForTimeout(1000)
await page.screenshot({ path: "/tmp/visual-test/B1-sign-in-desktop.png" })
await page.goto("https://fluttervibecode.dpdns.org/sign-up", { waitUntil: "domcontentloaded", timeout: 30000 })
await page.waitForTimeout(1000)
await page.screenshot({ path: "/tmp/visual-test/B3-sign-up-desktop.png" })
const m = await ctx.newPage()
await m.setViewportSize({ width: 390, height: 844 })
await m.goto("https://fluttervibecode.dpdns.org/sign-in", { waitUntil: "domcontentloaded", timeout: 30000 })
await m.waitForTimeout(800)
await m.screenshot({ path: "/tmp/visual-test/B2-sign-in-mobile.png" })
console.log("done")
await browser.close()
